<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Authors>Alireza Vafi</Authors>
        <Description>An extended persian tools based on community open source projects</Description>
        <PackageProjectUrl>https://github.com/alirezavafi/persian-plus</PackageProjectUrl>
        <PackageLicenseUrl>https://github.com/alirezavafi/persian-plus</PackageLicenseUrl>
        <PackageVersion>1.7.1</PackageVersion>
        <PackageId>Persian.Plus</PackageId>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <AssemblyName>Persian.Plus</AssemblyName>
        <RootNamespace>Persian.Plus</RootNamespace>
        <TargetFrameworks>net10.0;net8.0;net9.0</TargetFrameworks>
    </PropertyGroup>

    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="\" />
    </ItemGroup>

</Project>
